---
apiVersion: v1
kind: Template
metadata:
  name: standardInfraConfig-batch-template
objects:
- apiVersion: scheduling.k8s.io/v1beta1
  kind: PriorityClass
  metadata:
    name: production
  value: 10000
  globalDefault: false
  description: "This priority class should be used for Production service pods only."
- apiVersion: scheduling.k8s.io/v1beta1
  kind: PriorityClass
  metadata:
    name: qe
  value: 1000
  globalDefault: false
  description: "This priority class should be used for QE service pods only."
- apiVersion: scheduling.k8s.io/v1beta1
  kind: PriorityClass
  metadata:
    name: engineering
  value: 100
  globalDefault: false
  description: "This priority class should be used for Engineering service pods only."