---
apiVersion: v1
kind: Template
metadata:
  name: addressPlan-batch-template
objects:
- apiVersion: admin.enmasse.io/v1beta2
  kind: AddressPlan
  metadata:
    name: topic
    labels:
      app: enmasse
  spec:
    displayName: topic
    addressType: topic
    resources:
      router: ${{ROUTER_SLICE}}
      broker: ${{BROKER_SLICE}}
parameters:
- name: ROUTER_SLICE
  required: true
- name: BROKER_SLICE
  required: true