---
apiVersion: v1
kind: Template
metadata:
  name: addressSpacePlan-batch-template
objects:
- apiVersion: admin.enmasse.io/v1beta2
  kind: AddressSpacePlan
  metadata:
    name: perm
    labels:
      app: enmasse
  spec:
    displayName: Perm
    displayOrder: 0
    infraConfigRef: default
    addressSpaceType: standard
    resourceLimits:
      router: 20.0
      broker: 10.0
      aggregate: 30.0
    addressPlans:
    - results
    - alerts
