---
apiVersion: v1
kind: Template
metadata:
  name: addressPlan-batch-template
objects:
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: perm.results${CUSTOMER_ID}
  spec:
    address: results${CUSTOMER_ID}
    type: queue
    plan: results
parameters:
- name: CUSTOMER_ID
  required: true

