---
apiVersion: v1
kind: Template
metadata:
  name: addressPlan-batch-template
objects:
- apiVersion: admin.enmasse.io/v1beta2
  kind: AddressPlan
  metadata:
    name: ${PLAN_NAME}
    labels:
      app: enmasse
  spec:
    displayName: ${PLAN_NAME}
    addressType: anycast
    resources:
      router: ${{ROUTER_SLICE}}
      broker: 0
parameters:
- name: PLAN_NAME
  required: true
- name: ROUTER_SLICE
  required: true