---
apiVersion: v1
kind: Template
metadata:
  name: users-template
objects:
  - apiVersion: user.enmasse.io/v1beta1
    kind: MessagingUser
    metadata:
      name: ${ADDRESS_SPACE}.${USERNAME}
      labels:
        app: enmasse
    spec:
      username: ${USERNAME}
      authentication:
        type: password
        password: ${PASSWORD}
      authorization:
        - addresses: ["inputonline", "inputbatch"]
          operations: ["recv"]
        - addresses: ["alerts"]
          operations: ["send"]
        - addresses: ["results${CUSTOMER_ID}"]
          operations: ["send"]
parameters:
  - name: ADDRESS_SPACE
    required: true
  - name: USERNAME
    required: true
  - name: PASSWORD
    required: true
  - name: CUSTOMER_ID
    required: true