---
apiVersion: v1
kind: Template
metadata:
  name: standardInfraConfig-batch-template
objects:
- apiVersion: admin.enmasse.io/v1beta1
  kind: StandardInfraConfig
  metadata:
    name: default
    labels:
      app: enmasse
  spec:
    admin:
      resources:
        memory: 512Mi
    router:
      minReplicas: 3
      resources:
        memory: 256Mi
      linkCapacity: 250
    broker:
      resources:
        memory: 512Mi
        storage: 5Gi
      addressFullPolicy: PAGE