apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: enmasse
    prometheus: k8s
  name: prometheus-k8s
  annotations: 
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus-k8s"}}'
