apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
    prometheus: k8s
    role: alert-rules
  name: prometheus-k8s-rules
spec:
  groups:
  - name: ComponentHealth
    rules:

    - record: address_spaces_ready_total
      expr: sum(address_space_status_ready) by (service,namespace)
    - record: address_spaces_not_ready_total
      expr: sum(address_space_status_not_ready) by (service,namespace)

    - record: component_health
      expr: up{job="address-space-controller"} or on(namespace) (1- absent(up{job="address-space-controller"}) )

    - record: component_health
      expr: up{job="api-server"} or on(namespace) (1- absent(up{job="api-server"}) )

    - alert: ComponentHealth
      annotations: 
        description: "{{ $labels.job }} has been down for over 5 minutes"
        severity: critical
      expr: component_health == 0
      for: 300s
    - alert: AddressSpaceHealth
      annotations:
        description: Address Space(s) have been in a not ready state for over 5 minutes
        value: "{{ $value }}"
        severity: warning
      expr: address_spaces_not_ready_total > 0
      for: 300s
    - alert: AddressHealth
      annotations:
        description: Address(s) have been in a not ready state for over 5 minutes
        value: "{{ $value }}"
        severity: warning
      expr: addresses_not_ready_total > 0
      for: 300s
    - alert: TerminatingPods
      annotations:
        description: Pod {{ $labels.pod }} has been in a terminating state for over 5 minutes
        severity: warning
      expr: kube_pod_container_status_terminated == 1
      for: 180s
    - alert: RestartingPods
      annotations:
        description: Pod {{ $labels.pod }} has restarted over 5 times in the last 10 minutes
        severity: warning
      expr: rate(kube_pod_container_status_restarts_total[10m]) * 600 > 5
    - alert: PendingPods
      annotations:
        description: Pod {{ $labels.pod }} has been in a pending phase for over 5 minutes.
        severity: warning
      expr: kube_pod_status_phase{phase="Pending"} == 1
      for: 180s
