apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: enmasse
    prometheus: k8s
  name: k8s
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: enmasse-infra
      port: web
  image: prom/prometheus:v2.4.3
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  containers:
  - image: ${OAUTH_PROXY_IMAGE}
    imagePullPolicy: IfNotPresent
    name: oauth-proxy
    ports:
    - containerPort: 8443
      name: proxy
    args:
    - --https-address=:8443
    - --provider=openshift
    - --openshift-service-account=prometheus-k8s
    - --upstream=http://localhost:9090
    - --tls-cert=/etc/tls/private/tls.crt
    - --tls-key=/etc/tls/private/tls.key
    - --cookie-secret=SECRET
    volumeMounts:
    - mountPath: /etc/tls/private
      name: secret-prometheus-proxy-cert
  secrets:
  - prometheus-proxy-cert
