apiVersion: v1
kind: Route
metadata:
  labels:
    app: enmasse
  name: prometheus-k8s
spec:
  port:
    targetPort: proxy
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: prometheus-k8s
